#!/bin/bash

# Ansible??? No sorry I don't know her 💁

set -e

### OS X

defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

## Disable Caps Lock in preparation for installing Seil (which will remap it to Esc)
#  (https://apple.stackexchange.com/a/88096)
#  First, ugly script to get our keyboard's VendorID and ProductID:
read kb_vendorid kb_productid < \
    <(ioreg -n IOHIDKeyboard -r \
      | grep -e 'class IOHIDKeyboard' -e VendorID\" -e Product \
      | sed -nE 's/^.*= *//p' \
      | tail -n 2 \
      | paste -s -)

# Now disable Caps Lock (map key 0 to action -1)
defaults -currentHost write -g \
    com.apple.keyboard.modifiermapping.${kb_vendorid}-${kb_productid}-0 \
    -array-add $(printf '%s' '<dict>' \
                                '<key>HIDKeyboardModifierMappingDst</key>' \
                                '<integer>-1</integer>' \
                                '<key>HIDKeyboardModifierMappingSrc</key>' \
                                '<integer>0</integer>' \
                             '</dict>')



### Homebrew

brew_install=.__ben_init_brew.rb
curl -fsSLo $brew_install https://raw.githubusercontent.com/Homebrew/install/master/install
read -n1 -rsp $'Opening Homebrew install script in vim. Verify contents, save and quit to continue. Result is piped into ruby.\n\nPress any key to continue...\n'
vim $brew_install
ruby $brew_install
rm $brew_install

# GNU rm(1) and co
brew install coreutils

for x in gcc rlwrap wget vim gnupg \
         python python3 leiningen node \
         trash hub heroku-toolbelt planck; do
    brew install $x
done

brew install caskroom/cask/brew-cask

brew cask install seil


# Install remaining apps (eg spotify) with install-apps script


# wrap git for the rest of this script
eval "$(hub alias -s)"


# Remap Caps Lock to Escape
/Applications/Seil.app/Contents/Library/bin/seil set keycode_capslock 53


### Setup Vim plugins

vim_setup() {

    # Pathogen
    mkdir -p ~/.vim/autoload ~/.vim/bundle
    curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

    # Everything else
    cd ~/.vim/bundle
    git clone othree/html5.vim
    git clone hail2u/vim-css3-syntax
    git clone kchmck/vim-coffee-script
    git clone digitaltoad/vim-jade
    git clone elzr/vim-json
    git clone plasticboy/vim-markdown
    git clone guns/vim-clojure-static
    git clone fatih/vim-go
    git clone rust-lang/rust.vim

    git clone tpope/vim-repeat
    git clone tpope/vim-surround
    git clone bling/vim-airline

}
vim_setup


### Python

echo 'Sudo required to ensure proper ownership on python library location'
sudo chown -R $(basename ~):admin /usr/local/lib/python2.7
pip install virtualenv requests


### TrueCrypt

wget https://www.grc.com/misc/truecrypt/TrueCrypt%207.1a%20Mac%20OS%20X.dmg
echo '16e6d7675d63fba9bb75a9983397e3fb610459a1  TrueCrypt 7.1a Mac OS X.dmg' | shasum --check
open 'TrueCrypt 7.1a Mac OS X.dmg'
