#!/bin/bash

### OS X

defaults write com.apple.finder _FXShowPosixPathInTitle -bool true


### Homebrew

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# GNU rm(1) and co
brew install coreutils
brew install rlwrap
brew install gcc

brew install node
brew install hub
brew install trash
brew install wget
brew install gnupg
brew install python
brew install python3
brew install leiningen
brew install go
brew install heroku-toolbelt
brew install vim
brew install exiftool
brew install httpie
brew install postgresql

brew cask install betterzipql
brew cask install google-chrome
brew cask install dropbox
brew cask install bartender
brew cask install spotify
brew cask install iterm2
brew cask install soundflower
brew cask install transmission
brew cask install flux
brew cask install geotag
brew cask install mplayerx

brew tap caskroom/versions
brew cask install lightroom3


# wrap git
eval "$(hub alias -s)"


### Setup Vim plugins

# Pathogen
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

# Everything else
cd ~/.vim/bundle
git clone othree/html5.vim
git clone hail2u/vim-css3-syntax
git clone kchmck/vim-coffee-script
git clone digitaltoad/vim-jade
git clone elzr/vim-json
git clone plasticboy/vim-markdown
git clone guns/vim-clojure-static
git clone fatih/vim-go
git clone rust-lang/rust.vim

git clone tpope/vim-repeat
git clone tpope/vim-surround


### Python

sudo easy_install pip
sudo -H pip install virtualenv


### TrueCrypt

wget https://www.grc.com/misc/truecrypt/TrueCrypt%207.1a%20Mac%20OS%20X.dmg
echo '16e6d7675d63fba9bb75a9983397e3fb610459a1  TrueCrypt 7.1a Mac OS X.dmg' | shasum --check
open 'TrueCrypt 7.1a Mac OS X.dmg'
