#!/bin/bash

set -e

for x in jq ocaml ghc cabal-install r go scala \
         exiftool postgresql httpie ffmpeg youtube-dl mobile-shell graphviz \
         the_silver_searcher tmux fzf maven reattach-to-user-namespace \
         poppler closure-compiler ; do
    brew install $x
done

# create Go path referred to in .bash_profile
mkdir -p ~/go

brew tap caskroom/versions

for x in betterzipql google-chrome dropbox bartender spotify iterm2 \
         transmission flux geotag mplayerx slack; do
    brew cask install $x
done

for x in typescript@next grunt-cli bower
    ; do
    npm install -g $x
done

for x in httpstat; do
    go get $x
done

pip install aws

curl https://sh.rustup.rs -sSf | sh
