#!/bin/bash

# Ansible??? No sorry I don't know her 💁

set -e

### OS X

defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool true


# Map <Caps Lock> -> <Escape>
#   @since 10.10 Sierra
#   @see [Apple TN2450](https://developer.apple.com/library/content/technotes/tn2450/_index.html)
read __hidcapslockesc < <(python -c "$(cat <<END
import json
print(json.dumps({
    "UserKeyMapping":[
        {
            "HIDKeyboardModifierMappingSrc": 0x700000039,
            "HIDKeyboardModifiedMappingDst": 0x700000029
        }
    ]
}))
END
)")
hidutil property --set "$__hidcapslockesc"


### Homebrew

brew_install=.__ben_init_brew.rb
curl -fsSLo $brew_install https://raw.githubusercontent.com/Homebrew/install/master/install
read -n1 -rsp $'Opening Homebrew install script in vim. Verify contents, save and quit to continue. Result is piped into ruby.\n\nPress any key to continue...\n'
vim $brew_install
ruby $brew_install
rm $brew_install
brew analytics off

# GNU rm(1) and co
brew install coreutils

for x in gcc rlwrap wget git vim gpg \
         python python3 leiningen node \
         trash hub heroku-toolbelt planck; do
    brew install $x
done

#brew install caskroom/cask/brew-cask


# Install remaining apps (eg spotify) with install-apps script


# wrap git for the rest of this script
eval "$(hub alias -s)"


### Setup Vim plugins

vim_setup() {

    # Pathogen
    mkdir -p ~/.vim/autoload ~/.vim/bundle
    curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

    # Everything else
    cd ~/.vim/bundle
    git clone cespare/vim-toml
    git clone digitaltoad/vim-jade
    git clone elzr/vim-json
    git clone fatih/vim-go
    git clone guns/vim-clojure-static
    git clone hail2u/vim-css3-syntax
    git clone isRuslan/vim-es6
    git clone kchmck/vim-coffee-script
    git clone leafgarland/typescript-vim
    git clone othree/html5.vim
    git clone plasticboy/vim-markdown
    git clone rust-lang/rust.vim

    git clone bling/vim-airline
    git clone haya14busa/incsearch.vim
    git clone scrooloose/nerdtree
    git clone tpope/vim-fireplace
    git clone tpope/vim-repeat
    git clone tpope/vim-surround

    git clone wincent/command-t
    cd command-t/ruby/command-t/ext/command-t
    ruby extconf.rb
    make

}
vim_setup


### Git autocompletion
wget -O ~/.git-completion https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
chmod +x ~/.git-completion



### Python

echo 'Sudo required to ensure proper ownership on python library location'
sudo chown -R $(basename ~):admin /usr/local/lib/python2.7
pip install virtualenv requests


### TrueCrypt

wget https://www.grc.com/misc/truecrypt/TrueCrypt%207.1a%20Mac%20OS%20X.dmg
echo '16e6d7675d63fba9bb75a9983397e3fb610459a1  TrueCrypt 7.1a Mac OS X.dmg' \
    | shasum --check \
    && open 'TrueCrypt 7.1a Mac OS X.dmg'
